name: Build and Deploy .NET 8 App to Azure VM

trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Name of your self-hosted agent pool in Azure DevOps

steps:
- task: PowerShell@2
  displayName: 'Stop AppPool'
  inputs:
    targetType: 'inline'
    script: '%SYSTEMROOT%\System32\inetsrv\appcmd stop apppool /apppool.name:"website"'

- task: PowerShell@2
  displayName: 'Checkout code'
  inputs:
    targetType: 'inline'
    script: 'echo Checkout is handled automatically in Azure Pipelines'

# Skip setup-dotnet if SDK is installed on VM

- task: PowerShell@2
  displayName: 'Restore dependencies'
  inputs:
    targetType: 'inline'
    script: 'dotnet restore'

- task: PowerShell@2
  displayName: 'Build'
  inputs:
    targetType: 'inline'
    script: 'dotnet build --configuration Release --no-restore'

- task: PowerShell@2
  displayName: 'Publish'
  inputs:
    targetType: 'inline'
    script: 'dotnet publish --configuration Release --output D:\website-master_temp\'

- task: PowerShell@2
  displayName: 'Deploy to IIS folder'
  inputs:
    targetType: 'inline'
    script: |
      Remove-Item -Recurse -Force D:\website-master\*
      Copy-Item -Path D:\website-master_temp\* -Destination D:\website-master\ -Recurse

- task: PowerShell@2
  displayName: 'Start AppPool'
  inputs:
    targetType: 'inline'
    script: '%SYSTEMROOT%\System32\inetsrv\appcmd start apppool /apppool.name:"website"'
