trigger:
- Main

pool:
  name: 'CICDTest'   # 🔑 Your self-hosted agent pool name

variables:
  buildConfiguration: 'Release'
  publishFolder: '$(Build.ArtifactStagingDirectory)\CICDTest-publish'
  iisFolder: 'D:\CICDTest'
  appPoolName: 'website'
  backupRoot: 'D:\website-backup'

stages:
- stage: Build
  displayName: 'Build CICDTest'
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'   # 🔑 Adjust to installed SDK version on your standalone agent
        installationPath: 'C:\dotnet'  # Optional if you have .NET already in PATH

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(publishFolder)'

- stage: Deploy
  displayName: 'Deploy CICDTest to IIS'
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - task: PowerShell@2
      displayName: 'Backup, Deploy, Rollback, Cleanup'
      inputs:
        targetType: 'inline'
        script: |
          $dateFolder = (Get-Date -Format 'yyyyMMdd')
          $timeFolder = (Get-Date -Format 'HHmmss')
          $backupPath = Join-Path "$(backupRoot)\$dateFolder" $timeFolder
          $iisFolder = "$(iisFolder)"
          $publishFolder = "$(publishFolder)"
          $appPoolName = "$(appPoolName)"

          if (-not (Test-Path $backupPath)) {
              New-Item -ItemType Directory -Path $backupPath -Force | Out-Null
          }

          try {
              Write-Host "Stopping app pool: $appPoolName"
              Stop-WebAppPool -Name $appPoolName

              if (Test-Path $iisFolder) {
                  Write-Host "Backing up current site to: $backupPath"
                  Copy-Item $iisFolder $backupPath -Recurse -Force
              }

              Write-Host "Clearing IIS folder: $iisFolder"
              Remove-Item -Path "$iisFolder\*" -Recurse -Force -ErrorAction SilentlyContinue

              Write-Host "Copying new publish files..."
              Copy-Item "$publishFolder\*" $iisFolder -Recurse -Force

              Write-Host "Starting app pool: $appPoolName"
              Start-WebAppPool -Name $appPoolName

              Write-Host "Cleaning up publish folder..."
              Remove-Item -Path "$publishFolder" -Recurse -Force -ErrorAction SilentlyContinue

              Write-Host "Cleaning old backups (older than 7 days)..."
              Get-ChildItem "$(backupRoot)" -Directory | ForEach-Object {
                  Get-ChildItem $_.FullName -Directory | Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-7) } | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
              }
          }
          catch {
              Write-Error "Deployment failed: $_"
              if (Test-Path $backupPath) {
                  Write-Host "Rolling back from: $backupPath"
                  Remove-Item -Path "$iisFolder\*" -Recurse -Force -ErrorAction SilentlyContinue
                  Copy-Item "$backupPath\*" $iisFolder -Recurse -Force
                  Start-WebAppPool -Name $appPoolName
                  Write-Host "Rollback completed."
              } else {
                  Write-Error "Rollback failed: no backup found."
              }
          }
